[features]
seeds = false
skip-lint = false

[programs.localnet]
element_nft = "ELeMNFTxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
marketplace = "MKTPLCExxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
registry = "REGSTRYxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[programs.devnet]
element_nft = "ELeMNFTxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
marketplace = "MKTPLCExxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
registry = "REGSTRYxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[programs.mainnet]
element_nft = "ELeMNFTxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
marketplace = "MKTPLCExxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
registry = "REGSTRYxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metadata.so"

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "spl_token.so"

[[test.genesis]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
program = "spl_associated_token_account.so"
